trigger:
  branches:
    include:
    - master  # Specify the branch to trigger the build

pool:
  vmImage: 'windows-latest'  # or 'macOS-latest' for a Mac environment

steps:
- script: |
    echo "Setting up Java..."
    export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
    export PATH=$JAVA_HOME/bin:$PATH
  displayName: 'Set up Java'

- script: |
    echo "Building the APK..."
    ./gradlew assembleRelease
  displayName: 'Build APK'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
