trigger:
  branches:
    include:
    - master  # The branch to trigger the build on

pool:
  name: 'self'  # Use the name of your agent pool
  demands:
    - agent.name -equals selfagent11  # Replace with your agent's name

steps:


- script: |
    echo "Setting up Java..."
    export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
    export PATH=$JAVA_HOME/bin:$PATH
  displayName: 'Set up Java'

- script: chmod +x ./gradlew
  displayName: 'Grant execute permission to gradlew'
  
- script: |
    echo "Building the APK..."
    ./gradlew assembleRelease --warning-mode all
  displayName: 'Build APK'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy APK files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
