trigger:
  branches:
    include:
    - master  # The branch to trigger the build on

pool:
  name: 'self'  # Use the name of your agent pool
  demands:
    - agent.name -equals selfagent11  # Replace with your agent's name

steps:

- checkout: self
- script: |
    ls -l
    chmod +x gradlew
    ./gradlew build
  displayName: 'Run Gradle Build'

- script: |
    echo "Setting up Java..."
    export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
    export PATH=$JAVA_HOME/bin:$PATH
  displayName: 'Set up Java'

- script: |
    echo "Building the APK..."
    ./gradlew assembleRelease
  displayName: 'Build APK'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy APK files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
