trigger:
  branches:
    include:
      - master  # The branch to trigger the build on

pool:
  name: 'self'  # Use the name of your agent pool
  demands:
    - agent.name -equals selfagent11  # Replace with your agent's name

steps:

- script: chmod +x ./gradlew
  displayName: 'Grant execute permission to gradlew'

- script: |
    echo "Stopping Gradle daemons and cleaning project..."
    ./gradlew --stop
    ./gradlew clean
  displayName: 'Stop Daemons and Clean Project'
